version: '3.8'
services:
    bot:
        build: .
        restart: always
        stop_signal: SIGINT
        network_mode: host
        env_file: .env
        volumes:
            - "./goods.json:/app/goods.json"
            - "./locales:/app/locales"
    db:
        image: mysql:latest
        env_file: .env
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
