version: '3.8'
services:
    bot:
        build: .
        restart: always
        stop_signal: SIGINT
        network_mode: host
        env_file: .env
        volumes:
            - "./goods.json:/app/goods.json"
            - "./locales:/app/locales"